import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Sidebar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>

      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="flex h-screen p-2 gap-x-5">
            <Sidebar />
            <div className="p-4 bg-background rounded-md w-full h-full border shadow ">
              <Header />
              <div className="w-full p-2 px-3 border my-2 shadow bg-white dark:bg-dark-card rounded-md h-[92%] overflow-y-auto">
                {children}
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
