import "./globals.css";
import "react-toastify/dist/ReactToastify.css"
import ToastifyClient from "@/components/libraries/ToastifyClient"
import { Suspense } from "react";


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<body>
				<Suspense>
					{children}
					<ToastifyClient
						position="top-right"
						autoClose={2500}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick={true}
						rtl={true}
						pauseOnFocusLoss
						draggable
						pauseOnHover
						theme="colored" />
				</Suspense>
			</body>
		</html >
	);
}
